DO $$ BEGIN
  CREATE ROLE authenticator LOGIN PASSWORD 'postgrest_local_only' NOINHERIT;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE ROLE web_anon NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER ROLE authenticator WITH LOGIN PASSWORD 'postgrest_local_only' NOINHERIT;
GRANT web_anon TO authenticator;
GRANT USAGE ON SCHEMA public TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO web_anon;
REVOKE SELECT ON TABLE usuarios FROM web_anon;
GRANT EXECUTE ON FUNCTION fn_registrar_venta(INTEGER, INTEGER, VARCHAR, JSONB) TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO web_anon;
